SET SERVEROUTPUT ON;
DECLARE
STATEMENT1 VARCHAR2(50);
BEGIN
STATEMENT1 :=  'STUDENTS OLDER THAN 19 WHO TOOK DRAWING:';      DBMS_OUTPUT.PUT_LINE(STATEMENT1);
FOR I IN (SELECT SNAME FROM STUDENT WHERE AGE>19 AND STUDENT.SNUM IN 
(SELECT SNUM FROM ENROLLED WHERE CNUM=3))
  LOOP
   DBMS_OUTPUT.PUT_LINE(I.SNAME);
  END LOOP;
END;
/
