SET SERVEROUTPUT ON;
DECLARE
K DECIMAL(5,3);	STRNG VARCHAR2(50);
BEGIN
STRNG := 'AVERAGE AGE OF STUDENTS WITH ME MAJOR=';
SELECT AVG(AGE) INTO K FROM STUDENT WHERE MAJOR='ME';
DBMS_OUTPUT.PUT_LINE(STRNG);	       DBMS_OUTPUT.PUT_LINE(K);
END;
/
