SET SERVEROUTPUT ON;
DECLARE
NUM NUMBER:=23;
STRNG VARCHAR2(30):='ZERO';
STRNG1 VARCHAR2(30):='ONE';
STRNG2 VARCHAR2(30):='TWO';
BEGIN
	IF MOD(NUM,3)=0 THEN
		DBMS_OUTPUT.PUT_LINE(STRNG);
	ELSIF MOD(NUM,3)=1 THEN
		DBMS_OUTPUT.PUT_LINE(STRNG1);	
	ELSE
		DBMS_OUTPUT.PUT_LINE(STRNG2);
	END IF;
END;
/