SET VERIFY OFF;
SET SERVEROUTPUT ON;
DECLARE
A MONEY.TAKA %TYPE:=&X;
B MONEY.TAKA %TYPE:=&Y;
C MONEY.TAKA %TYPE;

BEGIN
C := A+B;
IF C<170 THEN
	INSERT INTO MONEY VALUES(7,'A',C+10);
ELSIF C>=170 AND C<=210 THEN
	INSERT INTO MONEY VALUES(7,'B',C+30);
ELSE
	INSERT INTO MONEY VALUES(7,'C',C);
END IF;
COMMIT;


END;
/