SET SERVEROUTPUT ON;
DECLARE
NUM NUMBER:=24;
STRNG VARCHAR2(30):='ZERO';
STRNG1 VARCHAR2(30):='ONE';
STRNG2 VARCHAR2(30):='TWO';
BEGIN
	CASE MOD(NUM,3)
	WHEN 0 THEN
		DBMS_OUTPUT.PUT_LINE(STRNG);
	WHEN 1 THEN
		DBMS_OUTPUT.PUT_LINE(STRNG1);	
	ELSE
		DBMS_OUTPUT.PUT_LINE(STRNG2);
	END CASE;
END;
/