SET SERVEROUTPUT ON;
DECLARE
PartsID parts.pid%TYPE:=&P_ID;
LeastSID supplier.sid%TYPE:=0;
ID supplier.sid%TYPE;
NAME supplier.sname%TYPE;
ADDR supplier.address%TYPE;

BEGIN
	FOR I IN (select * from(SELECT SID FROM RECORDS WHERE PID=PartsID ORDER BY RECORDS.COST ASC) where rownum<=1)LOOP
	LeastSID:=I.SID;
	END LOOP;
	
	SELECT SID,SNAME,ADDRESS
	INTO ID,NAME,ADDR
	FROM SUPPLIER
	WHERE SID=LeastSID;
	DBMS_OUTPUT.PUT_LINE('DETAILS OF SUPPLIER WHO CHARGES THE LOWEST:');
	DBMS_OUTPUT.PUT_LINE('ID:'||ID||' NAME:'||NAME||' ADDRESS:'||ADDR);
	
END;
/