--Question 2: Find the average age of students whose major is ME.
--Part B (with PL/SQL):
--Query:

SET SERVEROUTPUT ON;
DECLARE
K DECIMAL(5,3);	STRNG VARCHAR2(50);
BEGIN
STRNG := 'AVERAGE AGE OF STUDENTS WITH ME MAJOR=';
SELECT AVG(AGE) INTO K FROM STUDENT WHERE MAJOR='ME';
DBMS_OUTPUT.PUT_LINE(STRNG);	       DBMS_OUTPUT.PUT_LINE(K);
END;
/
