--Categorize and print the students into 3 categories according to their levels: Freshman(1), Junior(2) and Senior(3). Print their id, names and categories.
SET SERVEROUTPUT ON;
DECLARE
A STUDENT.SNUM %TYPE;
B STUDENT.SNAME %TYPE;
C STUDENT.SLEVEL %TYPE;
D VARCHAR2(20):='-';
E VARCHAR2(20):='FRESHMAN';
F VARCHAR2(20):='JUNIOR';
G VARCHAR2(20):='SENIOR';
BEGIN

FOR I IN(SELECT SNUM,SNAME,SLEVEL FROM STUDENT)
LOOP
	CASE
	WHEN I.SLEVEL=1 THEN
		DBMS_OUTPUT.PUT(I.SNUM);
		DBMS_OUTPUT.PUT(D);
		DBMS_OUTPUT.PUT(I.SNAME);
		DBMS_OUTPUT.PUT(D);
		DBMS_OUTPUT.PUT(E);
		DBMS_OUTPUT.NEW_LINE;
		
	WHEN I.SLEVEL=2 THEN
		DBMS_OUTPUT.PUT(I.SNUM);
		DBMS_OUTPUT.PUT(D);
		DBMS_OUTPUT.PUT(I.SNAME);
		DBMS_OUTPUT.PUT(D);
		DBMS_OUTPUT.PUT(F);	
		DBMS_OUTPUT.NEW_LINE;
		
	ELSE
		DBMS_OUTPUT.PUT(I.SNUM);
		DBMS_OUTPUT.PUT(D);
		DBMS_OUTPUT.PUT(I.SNAME);
		DBMS_OUTPUT.PUT(D);
		DBMS_OUTPUT.PUT(G);
		DBMS_OUTPUT.NEW_LINE;
		
	END CASE;

END LOOP;
END;
/ 